# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

# Test files aren't important for coverage
ignore:
  - "tests"
