---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "semver"
      - dependency-name: "crates-io"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
    rebase-strategy: "disabled"
