version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "semver"
      - dependency-name: "crates-io"
    rebase-strategy: "disabled"
