[package]
name = "finnish"
version = "0.1.0"
edition = "2021"
description = "Finnish is your personal finance manager."
repository = "github.com/nicolasauler/finnish"
keywords = ["finance", "personal finance", "budget", "money", "expenses", "income"]
categories = ["finance"]

[dependencies]
askama = { version = "0.12.1", features = ["with-axum", "serde-json"] }
askama_axum = "0.4.0"
axum = "0.7.4"
axum-helmet = "0.1.0"
axum-login = "0.13.1"
chrono = { version = "0.4.33", features = ["serde"] }
lazy_static = "1.4.0"
lettre = "0.11.4"
password-auth = "1.0.0"
plotly = { git = "https://github.com/nicolasauler/plotly.git" }
rand = "0.8.5"
regex = "1.10.2"
reqwest = { version = "0.11.24", features = ["json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
shuttle-axum = "0.38.0"
shuttle-runtime = { version = "0.38.0", default-features = false, features = ["colored"] }
shuttle-secrets = "0.38.0"
shuttle-shared-db = { version = "0.39.0", features = ["postgres", "sqlx"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio-rustls", "postgres", "chrono", "uuid"] }
strum = { version = "0.26.1", features = ["strum_macros", "derive"] }
time = "0.3.32"
tokio = { version = "1.36.0", features = ["full"] }
totp-rs = { version = "5.4.0", features = ["qr"] }
tower = "0.4.13"
tower-http = { version = "0.5.1", features = ["fs", "trace"] }
tower-sessions = "0.10.1"
tower-sessions-sqlx-store = { version = "0.10.0", features = ["postgres"] }
tower_governor = { version = "0.3.1", features = ["axum", "tracing"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uuid = { version = "1.7.0", features = ["v4", "fast-rng", "macro-diagnostics"] }
validator = { version = "0.16.1", features = ["derive"] }
zxcvbn = "2.2.2"
