[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
# Do not cancel the test run on the first failure.
fail-fast = false

[profile.default]
failure-output = "immediate-final"

[test-groups]
resource-limited = { max-threads = 1 }

[[profile.default.overrides]]
filter = 'test(features::invitations::)'
test-group = 'resource-limited'

[[profile.ci.overrides]]
filter = 'test(features::invitations::)'
test-group = 'resource-limited'
